<h1>this output is generated by node--news-clip.tpl.php </h1>
<?php
/**
 * @file sws-news-org-banner.tpl.php
 * Default theme implementation to display news organization banner/logo.
 *
 * Available variables:
 * - $node: The node object.
 * - $size: User-selected imagecache preset.
x* - $banner: themed banner image 
 * - $banner_link: banner linked to news org website
 * - $website: org website
 *
 * @see template_preprocess_sws_news_org_banner()
 */
?>
<?php if (!empty($banner_link)) : ?>
  <div class="news-clip-banner"><?php print $banner_link ?></div>
<?php elseif (!empty($banner)) : ?>
  <div class="news-clip-banner"><?php print $banner ?></div>
<?php endif; ?>

<?
/**
 * @file sws-newsclip-header.tpl.php
 * Default theme implementation to display news clip header. 
 *
 * Available variables:
 * - $node: The node object.
 * - $org_name
 * - $org_name_link
 * - $org_type
 * - $banner
 * - $banner_link
 * - $display_banner
 * - $org_website
 * - $clip_website
 * - $date
 * - $headline
 * - $headline_link
 * - $subhead
 * - $subhead_link
 * - $author: array of news contacts (if enabled)
 * - $by (string of authors)
 * 
 * @see template_preprocess_sws_newsclip()
 */
?>

<div class="news-clip-header <?php print "org-type-$org_type"?>">

  <div class="news-clip-banner">
    <?php if ($display_banner && $banner_link) : ?>
      <div class="news-org-logo"><?php print $banner_link ?></div>
    <?php elseif ($display_banner && $banner) : ?>
      <div class="news-org-logo"><?php print $banner ?></div>
    <?php elseif ($org_name_link) : ?>
      <div class="news-org-name"><?php print $org_name_link ?></div>
    <?php else : ?>
      <div class="news-org-name"><?php print $org_name ?></div>
    <?php endif ; ?>
    <div class="news-clip-date">
      <?php print $date ?> 
    </div>
  </div><!-- /news-clip-banner -->

  <div class="news-clip-headline"><?php print $headline ?></div>
  <?php if ($subhead) : ?>
    <div class="news-clip-subhead"><?php print $subhead ?></div>
  <?php endif ?>

  <div class="news-clip-by-line clear-block">
    <?php if ($by) { ?>
      <div class='news-clip-author'>By <?php print $by ?></div> 
    <?php } elseif ($author) {
        $count = 0;
        foreach ($author as $name) {
          if (strlen($name) != 0) {
            $count++;
            $by = ($count == 1) ? 'By' : 'and';
            print "<div class='news-clip-by'>$by&nbsp;</div><div class='news-clip-author'>$name&nbsp;</div>";
          }
        }
      }
    ?>
  </div>
</div><!-- /news-clip-header -->

<?
/**
 * @file sws-newsclip-footer.tpl.php
 * Default theme implementation to display news clip footer.
 *
 * Available variables:
 * - $footer (defined by user)
 * 
 * @see template_preprocess_sws_newsclip_footer()
 */
?>
<?php if ($footer) : ?>
  <div class="news-clip-footer"><?php print $footer ;?></div>
<?php endif; ?>
