<?php

include_once('press_releases.features.inc');

/**
 * Implementation of hook_menu().
 */
function press_releases_menu() {
  $items = array();

  $items['admin/settings/press_releases'] = array(
    'title' => t('Press Release Settings'), 
    'description' => t('Header/Footer Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('press_releases_admin_settings'),
    'access arguments' => array('administer sws'), 
    'type' => MENU_NORMAL_ITEM,
    'file' => 'press_releases.admin.inc', 
  );

  return $items;
}

