<?php
/**
 * @file sign_on_letters.install
 */
/**
 * Implementation of hook_install().
 */
function sign_on_letters_install() {
  // Set up captcha for signatory content type forms.  
  db_query("INSERT INTO {captcha_points} (form_id) "
    ."VALUES ('signatory_node_form') ");
}

/**
 * Implementation of hook_uninstall().
 */
function sign_on_letters_uninstall() {
  db_query("DELETE FROM {captcha_points} "
    ."WHERE form_id = 'signatory_node_form' ");
}
