<?php

include_once('news_clips.features.inc');

/**
 * Implementation of hook_menu().
 */
function news_clips_menu() {
  $items = array();

  $items['admin/settings/news_clips'] = array(
    'title' => t('News Clips Settings'), 
    'description' => t('News Clip Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('news_clips_admin_settings'),
    'access arguments' => array('administer sws'), 
    'type' => MENU_NORMAL_ITEM,
    'file' => 'news_clips.admin.inc', 
  );

  return $items;
}

