<?php

include_once('slideshow_panoramic_4_nav.features.inc');

/**
 * Override views_slideshow theme function.
 * 
 * next slide link
 */
function phptemplate_views_slideshow_singleframe_control_next($id, $view, $options) {
    $output = '<a href="#" id="views_slideshow_singleframe_next_' . $id . '" class="views_slideshow_singleframe_next">';
    $path = drupal_get_path('module', 'slideshow_panoramic_4_nav');
    $output .= '<img src="'. $path .'/theme/images/arrow-left.png" alt="slideshow scroll down" />';
    $output .= "</a>\n";
    return $output; 
}

/**
 * Override views_slideshow theme function.
 *
 * previous slide link
 */
/*
function phptemplate_views_slideshow_singleframe_control_previous($id, $view, $options) {
    return '<a href="#" id="views_slideshow_singleframe_prev_' . $id . '" class="views_slideshow_singleframe_previous">' . t('NEW_NAME_OF_PREVIOUS_BUTTON') . "</a>\n";
}
// */

/**
 * Override views_slideshow theme function.
 *
 * pause/play slideshow link
 */
/*
function phptemplate_views_slideshow_singleframe_control_pause($id, $view, $options) {
  return '<a href="#" id="views_slideshow_singleframe_playpause_' . $id . '" class="views_slideshow_singleframe_pause">' . t('NEW_NAME_OF_NEXT_BUTTON') . "</a>\n";
}
// */

/**
 * Implementation of hook_init().
 */
function slideshow_panoramic_4_nav_init(){
  $path = drupal_get_path('module', 'slideshow_panoramic_4_nav');
  $file_path = $path .'/theme/slideshow_panoramic_4_nav.css';
  drupal_add_css($file_path);
}

/**
 * Implementation of hook_form_alter()
 */
 /*
function slideshow_panoramic_4_nav_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'subtheme_form') {
    $form['slideshow_panoramic_4_nav'] = array(
      '#type' => 'fieldset',
      '#title' => t('Panoramic Slideshow (with Navigation)'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );  

    // TODO CONTINUE HERE WITH SUBTHEME OVERRIDES FOR CSS ELEMENTS
  }
}
// */
