<?php

include_once('fcp_sitemanagement.features.inc');

/**
 * Implementation of hook_enable().
 */
function fcp_sitemanagement_enable() {
  // update admin toolbar
  if(function_exists('fcontrolpanel_admin_toolbar')) {
    fcontrolpanel_admin_toolbar('enable');  
  }
}

/**
 * Implementation of hook_disable().
 */
function fcp_sitemanagement_disable() {
  // update admin toolbar
  if(function_exists('fcontrolpanel_admin_toolbar')) {
    fcontrolpanel_admin_toolbar('disable');  
  }
}
