<?php

include_once('slideshow_panoramic_3.features.inc');

/**
 * Implementation of hook_init().
 */
function slideshow_panoramic_3_init(){
  $path = drupal_get_path('module', 'slideshow_panoramic_3');
  $file_path = $path .'/theme/slideshow_panoramic_3.css';
  drupal_add_css($file_path);
}

/**
 * Implementation of hook_form_alter()
 */
 /*
function slideshow_panoramic_3_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'subtheme_form') {
    $form['slideshow_panoramic_4_nav'] = array(
      '#type' => 'fieldset',
      '#title' => t('Panoramic Slideshow (with Navigation)'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );  

    // TODO CONTINUE HERE WITH SUBTHEME OVERRIDES FOR CSS ELEMENTS
  }
}
// */
