<?php

include_once('slideshow_panoramic_3.features.inc');

/**
 * Implementation of hook_init().
 */
function slideshow_panoramic_3_init(){
  $path = drupal_get_path('module', 'slideshow_panoramic_3');
  $file_path = $path .'/theme/slideshow_panoramic_3.css';
  drupal_add_css($file_path);
}

/**
 * Implementation of hook_form_alter()
 */
function slideshow_panoramic_3_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'subtheme_form') {
    $form['slideshow_panoramic_3'] = array(
      '#type' => 'fieldset',
      '#title' => t('Panoramic Slideshow 3'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );  
    // #slideshow-panoramic-3-pic 
    $form['slideshow_panoramic_3']['pic'] = array(
      '#type' => 'fieldset',
      '#title' => t('Picture Settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );  
    $id = 'slideshow-panoramic-3-pic';  
    $properties = array(
      'border-top' => array('description' => 'default: 12px', 'title' => 'Top Border Width'),
      'border-left' => array('description' => 'default: 12px', 'title' => 'Left Border Width'),
      'border-right' => array('description' => 'default: 12px', 'title' => 'Right Border Width'),
      'border-bottom' => array('description' => 'default: 6px', 'title' => 'Bottom Border Width'),
      'border-style' => array('description' => 'default: solid', 'title' => 'Border Style'),
      'border-color' => array('description' => 'default: #fff', 'title' => 'Border Color'),
      'margin-left' => array('description' => 'default: 105px', 'title' => 'Left Margin Width'),
      'width' => array('description' => 'default: 784px', 'title' => 'Picture Width'),
    );
    foreach ($properties as $property => $details) {
      $element = 'subtheme_id--'. $id .'_'. $property;
      $form['slideshow_panoramic_3']['pic'][$element] = array(
        '#type' => 'textfield',
        '#title' => t($details['title']),
        '#default_value' => variable_get($element, NULL),
        '#description' => t($details['description']),
      );
    } 
    // #slideshow-panoramic-3-description
    $form['slideshow_panoramic_3']['description'] = array(
      '#type' => 'fieldset',
      '#title' => t('Description'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );  
    $id = 'slideshow-panoramic-3-description';  
    $properties = array(
      'background-color' => array('description' => 'default: #1D1852', 'title' => 'Background Color'),
      'border-top' => array('description' => 'default: 6px', 'title' => 'Top Border Width'),
      'border-left' => array('description' => 'default: 12px', 'title' => 'Left Border Width'),
      'border-right' => array('description' => 'default: 12px', 'title' => 'Right Border Width'),
      'border-bottom' => array('description' => 'default: 12px', 'title' => 'Bottom Border Width'),
      'border-style' => array('description' => 'default: solid', 'title' => 'Border Style'),
      'border-color' => array('description' => 'default: #fff', 'title' => 'Border Color'),
      'margin-left' => array('description' => 'default: 105px', 'title' => 'Left Margin Width'),
      'text-align' => array('description' => 'default: center', 'title' => 'Description Area Text Alignment'),
      'width' => array('description' => 'default: 784px', 'title' => 'Description Area Width'),
    );
    foreach ($properties as $property => $details) {
      $element = 'subtheme_id--'. $id .'_'. $property;
      $form['slideshow_panoramic_3']['description'][$element] = array(
        '#type' => 'textfield',
        '#title' => t($details['title']),
        '#default_value' => variable_get($element, NULL),
        '#description' => t($details['description']),
      );
    } 
    // #slideshow-panoramic-3
    $form['slideshow_panoramic_3']['sp3'] = array(
      '#type' => 'fieldset',
      '#title' => t('Background'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );  
    $id = 'slideshow-panoramic-3';  
    $properties = array(
      'position' => array('description' => 'default: relative', 'title' => 'Position'),
      'background' => array('description' => 'default: url("images/slideshow-background.jpg") no-repeat scroll 0 0 #dae1e9', 'title' => 'Background'),
      'text-align' => array('description' => 'default: center', 'title' => 'Text Alignment'),
      'width' => array('description' => 'default: 996px', 'title' => 'Width'),
      'height' => array('description' => 'default: 400px', 'title' => 'Height'), 
      'overflow' => array('description' => 'default: hidden', 'title' => 'Overflow'),
    );
    foreach ($properties as $property => $details) {
      $element = 'subtheme_id--'. $id .'_'. $property;
      $form['slideshow_panoramic_3']['sp3'][$element] = array(
        '#type' => 'textfield',
        '#title' => t($details['title']),
        '#default_value' => variable_get($element, NULL),
        '#description' => t($details['description']),
      );
    } 
  }
}
