<?php

include_once('news_clips.features.inc');

/**
 * Custom code. Everything below here 
 * was added manually, not written by Features
 * module.
 */ 

/**
 * TODO Move hook_nodeapi code from sws.module here.
 */
/*
function news_clips_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'news_clip') {
    switch($op) {
      
      case 'view':
        // On page view and  newsclips/feed show themed fields

        // On newsclips/feed/full show all fields, e.g. to allow campaign site to subscribe to SH site.

        break;
    } 
  }
}
// */
